### ISSUE TITLE
Add support for obfuscated code

### ISSUE THREAD

**Issue by richie0866** [richie0866/Rostruct#24]
It might be possible to add support for obfuscated code, for specific obfuscators, by having a specific file type for it. It would get passed into its respective VM to load it and run it later.

Unfortunately, I don't know what I am talking about, so this will be on hold and looked into later.

Some examples with workflows:
* A private repo automatically obfuscates & zips up source code when releasing, then pushes the release to a public repo

**Comment by nekohacker591** [comment]
this is open source
also its unreadable is is

**Comment by richie0866** [comment]
Yooo thanks for reminding me
